[window]
dynamic_padding = true
padding = { x = 10, y = 10 }
dimensions = { columns = 150, lines = 40 }

[cursor]
blink_timeout = 0
blink_interval = 500
unfocused_hollow = false
style = { shape = "Underline", blinking = "On" }

[mouse]
hide_when_typing = true

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[colors.primary]
background = '#1E1F22'
foreground = '#EBEBEB'

[colors.cursor]
text = '#EBEBEB'
cursor = '#FF261E'

[colors.normal]
black   = '#0D0D0D'
red     = '#FF301B'
green   = '#A0E521'
yellow  = '#FFC620'
blue    = '#1BA6FA'
magenta = '#8763B8'
cyan    = '#21DEEF'
white   = '#EBEBEB'

[colors.bright]
black   = '#6D7070'
red     = '#FF4352'
green   = '#B8E466'
yellow  = '#FFD750'
blue    = '#1BA6FA'
magenta = '#A578EA'
cyan    = '#73FBF1'
white   = '#FEFEF8'
